version: "3"
services:
  tank-battles-client:
    build: .
    restart: unless-stopped

  tank-battles-swag:
    image: lscr.io/linuxserver/swag
    container_name: tank-battles-swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - URL=tankbattles.duckdns.org
      - VALIDATION=duckdns
      - DUCKDNSTOKEN=${DUCKDNSTOKEN}
      - STAGING=false
    volumes:
      - /home/ethan/data/tankbattles-swag:/config
      - ./swag-default.conf:/config/nginx/site-confs/default.conf
    ports:
    - 0.0.0.0:10007:443
    restart: unless-stopped
